# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Conoid < Formula
  desc "A simple HTTP server that can be used to serve static files. It also provides TCP tunnelling through https://localtunnel.me to bypass a firewall or NAT, enabling local development servers to be exposed to the internet."
  homepage ""
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/deestarks/conoid/releases/download/v0.0.1/conoid_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "ee7539f4d30dbf44a4b3a59aa047a83d3455fe8968e6fea3d8f17b23ff2fa91e"

      def install
        bin.install "conoid"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/deestarks/conoid/releases/download/v0.0.1/conoid_0.0.1_Darwin_arm64.tar.gz"
      sha256 "79579f1511c334b40a185c1e6e7913d81c26a32074f283d3cce7ed7c777bed86"

      def install
        bin.install "conoid"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/deestarks/conoid/releases/download/v0.0.1/conoid_0.0.1_Linux_x86_64.tar.gz"
      sha256 "dfd5fc67b8f833e9ca5f339748d2c4225a18fbf72d15563703fb68f38a81b58f"

      def install
        bin.install "conoid"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deestarks/conoid/releases/download/v0.0.1/conoid_0.0.1_Linux_arm64.tar.gz"
      sha256 "229ec10f3385d187883e718147e64f1c5527283f70e8b59774d454fbf14f6f4b"

      def install
        bin.install "conoid"
      end
    end
  end
end
